name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/project/infogroove/

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Build distribution artifacts
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token "${UV_PUBLISH_TOKEN}"
